### PR TITLE
LSP reimplementation

### PR DESCRIPTION
**Pull request by LPeter1997**
This PR reimplements the LSP library we depended on.

### CODE REVIEW

**Comment by alexrp** [comment]
@LPeter1997 Just out of curiosity, what were the reasons for switching away from OmniSharp's LSP implementation?

**Comment by LPeter1997** [comment]
@alexrp There were multiple reasons and it was a hard decision, I'll try to summarize our main points in short:
 * The O# lib wasn't updated with the LSP specs, 3.17 features were missing and we wanted to have inlay hints for example (AFAIK the O# langserver actually has some external extensions to support this)
 * Some of us had the feeling the library was way over-engineered for what it did. I tried to extend it to add inlay hints, but eventually gave up
 * The support is very poor, it doesn't look like the maintainers want to provide help for users. I've tried to reach out to them multiple times, with no luck. The sample provided is ok-ish to get started, but definitely not proper documentation.
 * When started this project, we agreed on the philosophy "as few dependencies as possible, and only stable ones if we need any", exactly to not to dig ourselves into holes like this. And well, we took the shortcut for the langserver and it came back to bite us. We learned our lesson.

**Comment by alexrp** [comment]
Do you think you might publish `Draco.Lsp` as a package independent of the rest of Draco? I suspect I might eventually run into similar issues in my PL project, and it would probably make a lot of sense to not duplicate efforts.

**Comment by LPeter1997** [comment]
We might publish it eventually, but currently it's a non-goal. It has nothing compiler-specific and it's easy to extend with functionality that's missing. In case anyone wants to do the separation, here's the short summary.

## Inner workings of LSP message generation
 * `external/lsp-specification` contains the cloned LSP spec repo with all the markdown that you can see on the website
 * `Draco.SourceGeneration` is the project we put our source generators into, there under `Lsp` we have the logic to
   * Merge the markdown docs through the include directives they contain
   * Parse the TS message contracts
   * Translate them to C# contracts
 * `Draco.SourceGeneration/Templates` contains the Scriban template for LSP contracts that drives the actual code generation from the C# model
 * Only types are generated that are listed under `LspModel.xml` of the consumer project. You don't need to list everything, dependencies are automatically resolved. For example, [this is what `Draco.Lsp` brings in currently](https://github.com/Draco-lang/Compiler/blob/main/src/Draco.Lsp/Model/LspModel.xml).

## Inner workings of the LSP lib
 * `Draco.Lsp` was meant to be dead simple and driven by attributes, once we have contracts
 * All the language-server logic that the user might care about is under `Draco.Lsp/Server`, everything outside that is mostly crud  for the communication
 * `ILanguageClient` is the proxy for the client, you can see the attributes simply define the path from the specs and the fact if something is a request or notification. If someone needs extra behavior towards the client, once contracts are registered for the message, it can be defined here
 * The core server capabilities are in `ILanguageServer`, which is essentially initialize and shutdown
 * All other capabilities are then defined in subfolders like `Language` or `TextDocument` and each individual capability is its own interface. Whatever capabilities then the server implements, those will be registered automatically.
 * In general, server capabilities define both a static capability and registration options for dynamic registration. Currently, we default to dynamic registration everywhere, so we default capabilities to null (but explicit implementation is still possible).
 * Requests to the client or server can take an optional `CancellationToken`. We didn't specify it for every request, only where we expected slower, cancellable operations to emerge, but just specifying it in the interface should be enough to add it.
 * Static and dynamic capability registration [happens here](https://github.com/Draco-lang/Compiler/blob/main/src/Draco.Lsp/Server/LanguageServerLifecycle.cs), where we intercept these basic lifecycle messages, so the user doesn't have to deal with them manually

## Using the LSP lib
 * Usage can be seen in `Draco.LanguageServer`, how someone would implement a language server based on `Draco.Lsp`
 * In essence, to start a server, you need a [total of 3 lines](https://github.com/Draco-lang/Compiler/blob/main/src/Draco.LanguageServer/Program.cs#L52)
 * Whatever interfaces the server implements, those are going to be its capabilities. If you specify static capabilities, they will be registered during initialization, otherwise they'll be registered dynamically after the `initialized` notification
 * The language server for our language can be found in `Draco.LanguageServer` as an example

## Thoughts on sharing this as a NuGet package
 * First off, my domain of interest and expertise isn't distributed systems, this is the first server-client thing/protocol I've implemented, there could be a lot of janky things
 * So far, usage is very positive, a new capability can be added to `Draco.Lsp` in a matter of minutes, but in case some unhandled construct pops up from the specs, the source generator will crash, or generate illegal code. Those need some inner knowledge to fix. This is relatively rare (so far), only happened once so far, since we started using this solution.
 * As you can see, to provide an end-user experience, ideally we'd have every message specified in `Draco.Lsp`. Currently we are only adding message types, when our langserver needs it.
 * I see a few ways of publishing this
   1. Publishing the contract generator that can be torn out of `Draco.SourceGeneration`. This would not give anything outside the LSP message contracts, but it also saves tremendous amounts of work if someone wants to reimplement their own logic layer.
   2. Publishing `Draco.Lsp`. This would mean that only capabilities would be exposed to the consumer, that we added into this project. **If people are willing to contribute the endpoint specs they need, this would be the most ideal path by far, and would be a legit O# replacement**.
   3. Publishing something in-between, where we would factor out the core logic parts of `Draco.Lsp`, so the user wouldn't have to implement it, then they can specify what contracts to generate and what capability interfaces they want.
 * Personally I'd go with option 2, but only if people are willing to type out the message names in the interfaces and open a PR with it. We are trying to maintain a language project, it will be hard already tackling bugs that might pop up when others start using this, we wouldn't want to burn our free-time on writing out the remaining message specs that our server might never use.

**Pull request merged**
